#pragma once

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(uiDebug)
Q_DECLARE_LOGGING_CATEGORY(gameDebug)
Q_DECLARE_LOGGING_CATEGORY(resourceDebug)
Q_DECLARE_LOGGING_CATEGORY(moveDebug)
Q_DECLARE_LOGGING_CATEGORY(boardDebug)
